        // ── JG named presets (author-curated) ──

        Preset("JG Dub Wave", .developerPatches,
               subtitle: "Author recording · dubwise low end · Replay × 5 motion", [
                Voice(
                    hz: 329.66,
                    pan: -0.84,
                    wave: .sample,
                    amp: 0.04,
                    drive: 2.10,
                    startDelaySec: 15,
                    playDurationSec: 180,
                    replayCount: 2,
                    filter: FilterState(type: .lowpass, cutoffHz: 959, q: 1.84),
                    reverb: ReverbState(decaySec: 1.10, mix: 0.26),
                    delay: DelayState(timeSec: 0.52, feedback: 0.24, mix: 0.41),
                    chorus: ChorusState(rateHz: 0.46, depth: 0.37, width: 0.82, mix: 0.54),
                    grain: GrainState(sizeMs: 63, densityHz: 9.90, jitter: 0.54, panSpread: 0.77),
                    bundledSampleName: "JG Dub Wave",
                    grainSamplePosFrac: 0.69,
                    grainSamplePosJitter: 0.15,
                    lfos: [
                    LfoState(shape: .square,
                         targets: [.pan],
                         rateHz: 1.12,
                         depth: 0.12),
                    LfoState(shape: .sine,
                         targets: [.pitch],
                         rateHz: 0.03,
                         depth: 0.39),
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 1.26,
                         depth: 0.47),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch, .amplitude, .fmIndex],
                         rateHz: 1.49,
                         depth: 0.21)
                ]
                ),
                Voice(
                    hz: 61.27,
                    pan: 0.10,
                    wave: .sine,
                    amp: 0.59,
                    drive: 1.38,
                    reverb: ReverbState(decaySec: 4.71, mix: 0.30),
                    delay: DelayState(timeSec: 0.30, feedback: 0.40, mix: 0.14),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.21),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.None, .pitch],
                         rateHz: 0.47,
                         depth: 0.10),
                    LfoState(shape: .sampleAndHold,
                         targets: [.None, .pitch],
                         rateHz: 0.16,
                         depth: 1),
                    LfoState(shape: .sine,
                         targets: [.None, .fmIndex],
                         rateHz: 0.05,
                         depth: 0.44),
                    nil
                ]
                ),
                Voice(
                    hz: 123.47,
                    pan: -0.10,
                    wave: .sample,
                    amp: 0.99,
                    drive: 3.77,
                    startDelaySec: 30,
                    playDurationSec: 180,
                    replayCount: 3,
                    reverb: ReverbState(decaySec: 4.75, mix: 0.49),
                    delay: DelayState(timeSec: 0.70, feedback: 0.67, mix: 0.66),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.19),
                    bundledSampleName: "JG Dub Wave-2",
                    lfos: [
                    nil,
                    LfoState(shape: .sampleAndHold,
                         targets: [.None, .pitch],
                         rateHz: 0.32,
                         depth: 0.69),
                    LfoState(shape: .sine,
                         targets: [.None, .amplitude],
                         rateHz: 0.04,
                         depth: 0.48),
                    nil
                ]
                ),
                Voice(
                    hz: 138.59,
                    pan: 0.30,
                    wave: .sine,
                    startDelaySec: 120,
                    playDurationSec: 60,
                    replayCount: 5,
                    reverb: ReverbState(decaySec: 2, mix: 0.66),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0),
                    lfos: [
                    LfoState(shape: .square,
                         targets: [.None, .amplitude],
                         rateHz: 1.53,
                         depth: 0.46),
                    LfoState(shape: .sampleAndHold,
                         targets: [.None, .pitch],
                         rateHz: 0.42,
                         depth: 0.49),
                    nil,
                    nil
                ]
                )
               ]),

        Preset("JG Interrupted", .developerPatches,
               subtitle: "Vocal granular at high pos jitter · pulsing delay · Aeolian", [
                Voice(
                    hz: 440,
                    pan: -0.30,
                    wave: .sample,
                    amp: 0.44,
                    drive: 1.76,
                    startDelaySec: 15,
                    playDurationSec: 60,
                    replayCount: 2,
                    filter: FilterState(type: .lowpass, cutoffHz: 4060, q: 2.09),
                    reverb: ReverbState(decaySec: 3.58, mix: 0.12),
                    delay: DelayState(timeSec: 0.09, feedback: 0.87, mix: 0.96),
                    chorus: ChorusState(rateHz: 0.21, depth: 0.21, width: 0.68, mix: 0.18),
                    grain: GrainState(sizeMs: 487, densityHz: 6.38, jitter: 0.44, panSpread: 0.78),
                    bundledSampleName: "JG Dub Wave",
                    sampleGranular: true,
                    grainSamplePosFrac: 0.70,
                    lfos: [
                    nil,
                    LfoState(shape: .sampleAndHold,
                         targets: [.amplitude, .cutoff, .fmIndex],
                         rateHz: 0.50,
                         depth: 0.51),
                    LfoState(shape: .sine,
                         targets: [.cutoff, .pan],
                         rateHz: 0.30,
                         depth: 0.71),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 8.00,
                         depth: 0.96)
                ]
                ),
                Voice(
                    hz: 105.84,
                    pan: 0.10,
                    wave: .sine,
                    amp: 0.13,
                    drive: 1.58,
                    playDurationSec: 180,
                    replayCount: 2,
                    delay: DelayState(timeSec: 0.30, feedback: 0.64, mix: 0.60),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.07),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.03,
                         depth: 0.58),
                    nil,
                    LfoState(shape: .sine,
                         targets: [.cutoff],
                         rateHz: 0.12,
                         depth: 0.44),
                    LfoState(shape: .sine,
                         targets: [.pitch],
                         rateHz: 0.30,
                         depth: 0.05)
                ],
                    drift: DriftVoiceConfig(pitchMode: .downUp, panMode: .static)
                ),
                Voice(
                    hz: 113.22,
                    pan: -0.10,
                    wave: .sine,
                    amp: 0.14,
                    drive: 1.18,
                    startDelaySec: 30,
                    playDurationSec: 180,
                    replayCount: 2,
                    reverb: ReverbState(decaySec: 7.26, mix: 0.52),
                    delay: DelayState(timeSec: 0.97, feedback: 0.72, mix: 0.80),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.20),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.25,
                         depth: 0.18),
                    LfoState(shape: .sampleAndHold,
                         targets: [.amplitude],
                         rateHz: 0.50,
                         depth: 0.75),
                    LfoState(shape: .sine,
                         targets: [.cutoff, .filterQ, .fmIndex],
                         rateHz: 0.08,
                         depth: 0.46),
                    nil
                ],
                    drift: DriftVoiceConfig(pitchMode: .upDown, panMode: .static)
                ),
                Voice(
                    hz: 122.25,
                    pan: 0.30,
                    wave: .triangle,
                    amp: 0.29,
                    drive: 1.98,
                    startDelaySec: 60,
                    playDurationSec: 60,
                    replayCount: 2,
                    filter: FilterState(type: .highpass, cutoffHz: 284, q: 4.71),
                    delay: DelayState(timeSec: 0.72, feedback: 0.65, mix: 0.29),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan, .filterQ, .fmIndex],
                         rateHz: 0.06,
                         depth: 0.59),
                    nil,
                    nil,
                    nil
                ],
                    drift: DriftVoiceConfig(pitchMode: .ocean, panMode: .static)
                )
               ]),

        Preset("JG JoG", .developerPatches,
               subtitle: "Author recording · JoG sample-granular study", [
                Voice(
                    hz: 110,
                    pan: -0.30,
                    wave: .sample,
                    amp: 0.89,
                    drive: 1.63,
                    startDelaySec: 30,
                    playDurationSec: 180,
                    replayCount: 3,
                    filter: FilterState(type: .lowpass, cutoffHz: 4277, q: 3.98),
                    reverb: ReverbState(decaySec: 4.49, mix: 0.69),
                    delay: DelayState(timeSec: 0.19, feedback: 0.56, mix: 0.34),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0),
                    grain: GrainState(sizeMs: 80, densityHz: 2.67, jitter: 0, panSpread: 0.50),
                    bundledSampleName: "JG JoG",
                    sampleGranular: true,
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.fxMix],
                         rateHz: 0.10,
                         depth: 0.88),
                    nil,
                    nil,
                    nil
                ]
                ),
                Voice(
                    hz: 138.59,
                    pan: 0.10,
                    wave: .sawtooth,
                    amp: 0.44,
                    startDelaySec: 60,
                    playDurationSec: 60,
                    replayCount: 5,
                    reverb: ReverbState(decaySec: 3.26, mix: 0.30),
                    delay: DelayState(timeSec: 0.25, feedback: 0.47, mix: 0.61),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.08),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.25,
                         depth: 0.24),
                    LfoState(shape: .triangle,
                         targets: [.amplitude],
                         rateHz: 0.10,
                         depth: 0.24),
                    LfoState(shape: .sine,
                         targets: [.cutoff],
                         rateHz: 0.19,
                         depth: 0.26),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 0.30,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .eighthT)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, panMode: .static, quantizeToScale: true)
                ),
                Voice(
                    hz: 174.61,
                    pan: -0.10,
                    wave: .sine,
                    amp: 0.47,
                    drive: 1.20,
                    filter: FilterState(type: .lowpass, cutoffHz: 2002, q: 1.52),
                    reverb: ReverbState(decaySec: 5.73, mix: 0.43),
                    delay: DelayState(timeSec: 0.30, feedback: 0.40, mix: 0.22),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.19),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.05,
                         depth: 0.26),
                    LfoState(shape: .sampleAndHold,
                         targets: [.amplitude, .filterQ, .cutoff],
                         rateHz: 0.04,
                         depth: 0.17),
                    LfoState(shape: .sine,
                         targets: [.cutoff, .fmIndex],
                         rateHz: 0.09,
                         depth: 0.46),
                    LfoState(shape: .sine,
                         targets: [.pitch],
                         rateHz: 1.00,
                         depth: 0.06)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, panMode: .static, quantizeToScale: true)
                ),
                Voice(
                    hz: 56.84,
                    pan: 0.30,
                    wave: .sawtooth,
                    amp: 0.50,
                    drive: 2.10,
                    filter: FilterState(type: .lowpass, cutoffHz: 471, q: 3.21),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.16),
                    lfos: [
                    nil,
                    LfoState(shape: .sine,
                         targets: [],
                         rateHz: 0.50,
                         depth: 0.06,
                         rateSyncEnabled: true,
                         rateDenomination: .sixteenth),
                    LfoState(shape: .sine,
                         targets: [.cutoff, .amplitude],
                         rateHz: 0.05,
                         depth: 0.54),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch, .filterQ],
                         rateHz: 0.14,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .half)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, panMode: .static, quantizeToScale: true)
                )
               ]),

        Preset("JG Low Intensity", .developerPatches,
               subtitle: "Quiet pad floor · gentle motion · low-amp meditative bed", [
                Voice(
                    hz: 110.00,
                    pan: 0,
                    wave: .triangle,
                    amp: 0.38,
                    drive: 1.96,
                    startDelaySec: 15,
                    playDurationSec: 180,
                    replayCount: 5,
                    filter: FilterState(type: .lowpass, cutoffHz: 2889, q: 9.37),
                    reverb: ReverbState(decaySec: 8.62, mix: 0.04),
                    delay: DelayState(timeSec: 0.67, feedback: 0.90, mix: 0.15),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.12),
                    grain: GrainState(sizeMs: 34, densityHz: 8, jitter: 0.60, panSpread: 0.50),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.11,
                         depth: 0.73),
                    LfoState(shape: .sine,
                         targets: [.amplitude, .filterQ, .cutoff, .fmIndex, .fxMix],
                         rateHz: 0.18,
                         depth: 0.61),
                    nil,
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 0.14,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .thirtySecond)
                ],
                    drift: DriftVoiceConfig(pitchMode: .up, panMode: .static, quantizeToScale: true)
                ),
                Voice(
                    hz: 220.64,
                    pan: 0.01,
                    wave: .granular,
                    amp: 0.48,
                    playDurationSec: 180,
                    replayCount: 5,
                    filter: FilterState(type: .lowpass, cutoffHz: 2400, q: 0.40),
                    reverb: ReverbState(decaySec: 7, mix: 0.27),
                    delay: DelayState(timeSec: 0.40, feedback: 0.40, mix: 0.20),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0),
                    grain: GrainState(sizeMs: 46, densityHz: 6.67, jitter: 0, panSpread: 1),
                    lfos: [
                    nil,
                    nil,
                    LfoState(shape: .sine,
                         targets: [.cutoff, .filterQ],
                         rateHz: 0.08,
                         depth: 0.29),
                    LfoState(shape: .sine,
                         targets: [.pitch, .fmIndex],
                         rateHz: 0.47,
                         depth: 0.39)
                ],
                    drift: DriftVoiceConfig(pitchMode: .down, panMode: .static)
                ),
                Voice(
                    hz: 220.80,
                    pan: 0.50,
                    wave: .granular,
                    amp: 0.31,
                    playDurationSec: 180,
                    replayCount: 5,
                    filter: FilterState(type: .lowpass, cutoffHz: 2417, q: 0.40),
                    reverb: ReverbState(decaySec: 9.47, mix: 0.27),
                    delay: DelayState(timeSec: 0.40, feedback: 0.40, mix: 0.20),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0),
                    grain: GrainState(sizeMs: 58, densityHz: 3.33, jitter: 0.61, panSpread: 0.85),
                    lfos: [
                    nil,
                    nil,
                    LfoState(shape: .sine,
                         targets: [.cutoff, .filterQ],
                         rateHz: 0.08,
                         depth: 0.18),
                    nil
                ],
                    drift: DriftVoiceConfig(pitchMode: .up, panMode: .static)
                ),
                Voice(
                    hz: 159.16,
                    pan: 0.03,
                    wave: .sawtooth,
                    amp: 0.49,
                    drive: 2.42,
                    startDelaySec: 60,
                    playDurationSec: 180,
                    replayCount: 5,
                    filter: FilterState(type: .lowpass, cutoffHz: 509, q: 1.93),
                    reverb: ReverbState(decaySec: 6.98, mix: 0.43),
                    delay: DelayState(timeSec: 0.60, feedback: 0.67, mix: 0.78),
                    chorus: ChorusState(rateHz: 2.03, depth: 0.54, width: 0.47, mix: 0.22),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan, .fxMix],
                         rateHz: 0.23,
                         depth: 0.73),
                    LfoState(shape: .sine,
                         targets: [.fmIndex],
                         rateHz: 0.24,
                         depth: 0.14),
                    LfoState(shape: .triangle,
                         targets: [.cutoff],
                         rateHz: 0.91,
                         depth: 0.40),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch, .filterQ],
                         rateHz: 0.49,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .sixteenth)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, pitchAmount: 1.28, pitchPhase: 0.17, panMode: .glacial, panAmount: 0.81, panPhase: 0.85, quantizeToScale: true)
                )
               ]),

        Preset("JG Maybe Three", .developerPatches,
               subtitle: "G♯ Lydian S&H pitch · 7-note mode quantize showcase", [
                Voice(
                    hz: 207.65,
                    pan: 0.01,
                    wave: .granular,
                    amp: 0.47,
                    drive: 1.51,
                    playDurationSec: 180,
                    replayCount: 3,
                    filter: FilterState(type: .lowpass, cutoffHz: 3200, q: 0.70),
                    reverb: ReverbState(decaySec: 9, mix: 0.50),
                    delay: DelayState(timeSec: 0.19, feedback: 0.82, mix: 0.61),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0),
                    grain: GrainState(sizeMs: 89, densityHz: 1.33, jitter: 0, panSpread: 0.95),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.13,
                         depth: 0.53),
                    nil,
                    nil,
                    nil
                ]
                ),
                Voice(
                    hz: 261.63,
                    pan: 0.50,
                    wave: .sine,
                    amp: 0.39,
                    startDelaySec: 15,
                    playDurationSec: 180,
                    replayCount: 5,
                    filter: FilterState(type: .lowpass, cutoffHz: 3200, q: 0.70),
                    reverb: ReverbState(decaySec: 9, mix: 0.72),
                    delay: DelayState(timeSec: 0.76, feedback: 0.82, mix: 0.58),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0),
                    grain: GrainState(sizeMs: 80, densityHz: 8, jitter: 0, panSpread: 0.50),
                    lfos: [
                    nil,
                    nil,
                    nil,
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 1.00,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .quarter)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, panMode: .static, quantizeToScale: true)
                ),
                Voice(
                    hz: 293.66,
                    pan: -0.20,
                    wave: .triangle,
                    amp: 0.35,
                    drive: 2.95,
                    playDurationSec: 60,
                    replayCount: 5,
                    filter: FilterState(type: .lowpass, cutoffHz: 534, q: 2.42),
                    reverb: ReverbState(decaySec: 9, mix: 0.82),
                    delay: DelayState(timeSec: 0.73, feedback: 0.63, mix: 0.68),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.17),
                    grain: GrainState(sizeMs: 80, densityHz: 8, jitter: 0, panSpread: 0.50),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.39,
                         depth: 0.54),
                    nil,
                    LfoState(shape: .sine,
                         targets: [.cutoff, .filterQ, .fmIndex],
                         rateHz: 0.45,
                         depth: 0.67),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 0.32,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .sixteenth)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, panMode: .static, quantizeToScale: true)
                ),
                Voice(
                    hz: 71.49,
                    pan: 0.00,
                    wave: .sawtooth,
                    amp: 0.34,
                    drive: 1.44,
                    startDelaySec: 60,
                    playDurationSec: 180,
                    replayCount: 3,
                    filter: FilterState(type: .lowpass, cutoffHz: 767, q: 1.28),
                    reverb: ReverbState(decaySec: 9, mix: 0.61),
                    delay: DelayState(timeSec: 0.30, feedback: 0.58, mix: 0.38),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.15),
                    grain: GrainState(sizeMs: 80, densityHz: 8, jitter: 0, panSpread: 0.50),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.07,
                         depth: 0.28),
                    LfoState(shape: .sine,
                         targets: [.amplitude, .fxMix, .fmIndex],
                         rateHz: 0.79,
                         depth: 0.35,
                         rateSyncEnabled: true,
                         rateDenomination: .half),
                    LfoState(shape: .sine,
                         targets: [.cutoff, .filterQ],
                         rateHz: 0.21,
                         depth: 0.60,
                         rateDenomination: .eighth),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 6.94,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .eighth)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, panMode: .static, quantizeToScale: true)
                )
               ]),

        Preset("JG Ondulations", .developerPatches,
               subtitle: "Author recording · undulating sample-granular cloud", [
                Voice(
                    hz: 251.49,
                    pan: -0.27,
                    wave: .sample,
                    amp: 0.32,
                    drive: 1.76,
                    startDelaySec: 15,
                    playDurationSec: 180,
                    replayCount: 2,
                    filter: FilterState(type: .lowpass, cutoffHz: 644, q: 0.88),
                    reverb: ReverbState(decaySec: 2.04, mix: 0.24),
                    delay: DelayState(timeSec: 0.12, feedback: 0.02, mix: 0.38),
                    chorus: ChorusState(rateHz: 0.21, depth: 0.21, width: 0.68, mix: 0),
                    grain: GrainState(sizeMs: 213, densityHz: 21.52, jitter: 0.54, panSpread: 0.64),
                    bundledSampleName: "JG Dub Wave",
                    sampleGranular: true,
                    grainSamplePosFrac: 0.69,
                    grainSamplePosJitter: 0.15,
                    lfos: [
                    LfoState(shape: .square,
                         targets: [.pan],
                         rateHz: 1.04,
                         depth: 0.31),
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.68,
                         depth: 0.32),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 1.03,
                         depth: 0.32),
                    LfoState(shape: .square,
                         targets: [.pitch],
                         rateHz: 0.36,
                         depth: 0.11)
                ]
                ),
                Voice(
                    hz: 61.27,
                    pan: 0.10,
                    wave: .sine,
                    amp: 0.59,
                    drive: 1.38,
                    reverb: ReverbState(decaySec: 4.71, mix: 0.30),
                    delay: DelayState(timeSec: 0.30, feedback: 0.40, mix: 0.14),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.21),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.None, .pitch],
                         rateHz: 0.18,
                         depth: 0.04),
                    LfoState(shape: .square,
                         targets: [.None, .pitch],
                         rateHz: 0.41,
                         depth: 1),
                    nil,
                    nil
                ]
                ),
                Voice(
                    hz: 123.47,
                    pan: -0.10,
                    wave: .sample,
                    amp: 0.96,
                    drive: 2.73,
                    startDelaySec: 30,
                    playDurationSec: 180,
                    replayCount: 3,
                    reverb: ReverbState(decaySec: 4.75, mix: 0.37),
                    delay: DelayState(timeSec: 0.70, feedback: 0.67, mix: 0.57),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.19),
                    bundledSampleName: "JG Dub Wave-2",
                    lfos: [
                    nil,
                    LfoState(shape: .sampleAndHold,
                         targets: [.None, .pitch],
                         rateHz: 0.32,
                         depth: 0.69),
                    LfoState(shape: .sine,
                         targets: [.None, .amplitude],
                         rateHz: 0.04,
                         depth: 0.48),
                    nil
                ]
                ),
                Voice(
                    hz: 138.59,
                    pan: 0.30,
                    wave: .sine,
                    startDelaySec: 120,
                    playDurationSec: 60,
                    replayCount: 5,
                    reverb: ReverbState(decaySec: 2, mix: 0.66),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0),
                    lfos: [
                    LfoState(shape: .square,
                         targets: [.None, .amplitude],
                         rateHz: 1.53,
                         depth: 0.46),
                    LfoState(shape: .sampleAndHold,
                         targets: [.None, .pitch],
                         rateHz: 2.79,
                         depth: 1.00),
                    nil,
                    nil
                ]
                )
               ]),

        Preset("JG Small Steps", .developerPatches,
               subtitle: "Author recording · small-steps sample-granular", [
                Voice(
                    hz: 220,
                    pan: -0.40,
                    wave: .granular,
                    amp: 0.55,
                    drive: 1.29,
                    playDurationSec: 120,
                    replayCount: 0,
                    filter: FilterState(type: .lowpass, cutoffHz: 4200, q: 0.76),
                    reverb: ReverbState(decaySec: 6.58, mix: 0.86),
                    delay: DelayState(timeSec: 1.22, feedback: 0.90, mix: 0.98),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.09),
                    grain: GrainState(sizeMs: 23, densityHz: 5.33, jitter: 0, panSpread: 0.99),
                    grainSamplePosJitter: 0.37,
                    lfos: [
                    nil,
                    nil,
                    nil,
                    LfoState(shape: .sine,
                         targets: [.pitch, .fxMix],
                         rateHz: 0.67,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .half)
                ]
                ),
                Voice(
                    hz: 182.57,
                    pan: 0.40,
                    wave: .sample,
                    amp: 0.96,
                    drive: 1.77,
                    startDelaySec: 30,
                    playDurationSec: 120,
                    replayCount: 0,
                    filter: FilterState(type: .lowpass, cutoffHz: 2000, q: 2.06),
                    reverb: ReverbState(decaySec: 8, mix: 0.55),
                    delay: DelayState(timeSec: 0.75, feedback: 0.56, mix: 0.65),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.04),
                    grain: GrainState(sizeMs: 130, densityHz: 5.33, jitter: 0, panSpread: 0.85),
                    bundledSampleName: "JG Small Steps",
                    sampleGranular: true,
                    grainSamplePosJitter: 0.35,
                    lfos: [
                    nil,
                    nil,
                    LfoState(shape: .sine,
                         targets: [.cutoff, .filterQ],
                         rateHz: 0.30,
                         depth: 0.63),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 0.30,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .sixteenth)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, panMode: .static, quantizeToScale: true)
                ),
                Voice(
                    hz: 135.22,
                    pan: 0.90,
                    wave: .triangle,
                    amp: 0.20,
                    reverb: ReverbState(decaySec: 9.29, mix: 0.84),
                    delay: DelayState(timeSec: 0.53, feedback: 0.73, mix: 0.86),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.10),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan, .fmIndex, .amplitude],
                         rateHz: 0.08,
                         depth: 0.38),
                    LfoState(shape: .sine,
                         targets: [.cutoff, .filterQ],
                         rateHz: 0.06,
                         depth: 0.46),
                    LfoState(shape: .sine,
                         targets: [.cutoff, .fmIndex, .filterQ],
                         rateHz: 0.16,
                         depth: 0.67),
                    LfoState(shape: .sampleAndHold,
                         targets: [],
                         rateHz: 0.30,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .quarter)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, panMode: .static, quantizeToScale: true)
                ),
                Voice(
                    hz: 535.47,
                    pan: -0.00,
                    wave: .triangle,
                    amp: 0.27,
                    drive: 1.41,
                    filter: FilterState(type: .lowpass, cutoffHz: 3961, q: 1.00),
                    reverb: ReverbState(decaySec: 3.19, mix: 0.22),
                    delay: DelayState(timeSec: 0.48, feedback: 0.28, mix: 0.27),
                    chorus: ChorusState(rateHz: 1.82, depth: 0.31, width: 0.88, mix: 0.19),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.fxMix],
                         rateHz: 1.41,
                         depth: 0.56,
                         rateSyncEnabled: true,
                         rateDenomination: .half),
                    LfoState(shape: .triangle,
                         targets: [.amplitude, .filterQ, .cutoff, .fmIndex],
                         rateHz: 0.43,
                         depth: 0.30),
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 1.45,
                         depth: 0.46),
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.41,
                         depth: 0.19)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, pitchAmount: 0.61, pitchPhase: 0.11, panMode: .static, panAmount: 0.94, panPhase: 0.43, quantizeToScale: true)
                )
               ]),

        Preset("JG WalK", .developerPatches,
               subtitle: "Author recording · slower JoG sample-granular", [
                Voice(
                    hz: 110,
                    pan: 0.01,
                    wave: .sample,
                    amp: 0.89,
                    drive: 1.63,
                    startDelaySec: 30,
                    playDurationSec: 180,
                    replayCount: 3,
                    filter: FilterState(type: .lowpass, cutoffHz: 4277, q: 3.98),
                    reverb: ReverbState(decaySec: 3.35, mix: 0.56),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0),
                    grain: GrainState(sizeMs: 76, densityHz: 1.33, jitter: 0, panSpread: 0.50),
                    bundledSampleName: "JG JoG",
                    sampleGranular: true,
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.11,
                         depth: 0.40),
                    nil,
                    nil,
                    nil
                ]
                ),
                Voice(
                    hz: 138.59,
                    pan: 0.10,
                    wave: .sawtooth,
                    amp: 0.60,
                    startDelaySec: 60,
                    playDurationSec: 60,
                    replayCount: 5,
                    reverb: ReverbState(decaySec: 3.26, mix: 0.30),
                    delay: DelayState(timeSec: 0.25, feedback: 0.47, mix: 0.61),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.08),
                    lfos: [
                    nil,
                    LfoState(shape: .sine,
                         targets: [.amplitude, .fxMix],
                         rateHz: 0.07,
                         depth: 0.66),
                    LfoState(shape: .sine,
                         targets: [.cutoff],
                         rateHz: 0.19,
                         depth: 0.26),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 0.30,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .quarter)
                ],
                    drift: DriftVoiceConfig(pitchMode: .static, panMode: .static, quantizeToScale: true)
                ),
                Voice(
                    hz: 174.61,
                    pan: 0,
                    wave: .sine,
                    amp: 0.55,
                    reverb: ReverbState(decaySec: 4.37, mix: 0.23),
                    delay: DelayState(timeSec: 0.30, feedback: 0.40, mix: 0.26),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.13),
                    lfos: [
                    LfoState(shape: .triangle,
                         targets: [.pan],
                         rateHz: 0.25,
                         depth: 0.42),
                    LfoState(shape: .sine,
                         targets: [.amplitude],
                         rateHz: 0.06,
                         depth: 0.33),
                    LfoState(shape: .sine,
                         targets: [.cutoff, .fmIndex],
                         rateHz: 0.09,
                         depth: 0.46),
                    LfoState(shape: .sine,
                         targets: [.pitch],
                         rateHz: 1.00,
                         depth: 0.06)
                ]
                ),
                Voice(
                    hz: 56.84,
                    pan: 0.30,
                    wave: .sine,
                    amp: 0.83,
                    drive: 1.51,
                    filter: FilterState(type: .lowpass, cutoffHz: 6636, q: 3.21),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.16),
                    lfos: [
                    nil,
                    LfoState(shape: .sine,
                         targets: [.amplitude],
                         rateHz: 0.50,
                         depth: 0.06,
                         rateSyncEnabled: true,
                         rateDenomination: .sixteenth),
                    LfoState(shape: .sine,
                         targets: [.cutoff, .amplitude],
                         rateHz: 0.05,
                         depth: 0.54),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 0.14,
                         depth: 1,
                         rateSyncEnabled: true,
                         rateDenomination: .eighth)
                ]
                )
               ]),

        Preset("JG Whole Tone Wind", .developerPatches,
               subtitle: "Whole-tone stack · sample granular wind · Replay × 5", [
                Voice(
                    hz: 340.92,
                    pan: -0.33,
                    wave: .sample,
                    amp: 0.37,
                    drive: 1.76,
                    startDelaySec: 15,
                    playDurationSec: 180,
                    replayCount: 2,
                    filter: FilterState(type: .lowpass, cutoffHz: 644, q: 0.88),
                    reverb: ReverbState(decaySec: 2.04, mix: 0.24),
                    delay: DelayState(timeSec: 0.12, feedback: 0.02, mix: 0.38),
                    chorus: ChorusState(rateHz: 0.21, depth: 0.21, width: 0.68, mix: 0),
                    grain: GrainState(sizeMs: 213, densityHz: 21.52, jitter: 0.54, panSpread: 0.64),
                    bundledSampleName: "JG Dub Wave",
                    sampleGranular: true,
                    grainSamplePosFrac: 0.69,
                    grainSamplePosJitter: 0.15,
                    lfos: [
                    LfoState(shape: .square,
                         targets: [.pan],
                         rateHz: 1.04,
                         depth: 0.31),
                    LfoState(shape: .sine,
                         targets: [.pan],
                         rateHz: 0.68,
                         depth: 0.32),
                    LfoState(shape: .sampleAndHold,
                         targets: [.pitch],
                         rateHz: 1.03,
                         depth: 0.32),
                    LfoState(shape: .square,
                         targets: [.pitch],
                         rateHz: 0.36,
                         depth: 0.11)
                ]
                ),
                Voice(
                    hz: 110.00,
                    pan: 0.10,
                    wave: .sine,
                    amp: 0.49,
                    drive: 1.38,
                    reverb: ReverbState(decaySec: 4.71, mix: 0.30),
                    delay: DelayState(timeSec: 0.30, feedback: 0.40, mix: 0.14),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.21),
                    lfos: [
                    LfoState(shape: .sine,
                         targets: [.None, .pitch],
                         rateHz: 0.18,
                         depth: 0.04),
                    nil,
                    nil,
                    nil
                ]
                ),
                Voice(
                    hz: 123.47,
                    pan: -0.10,
                    wave: .sample,
                    amp: 0.75,
                    drive: 2.73,
                    startDelaySec: 30,
                    playDurationSec: 180,
                    replayCount: 3,
                    reverb: ReverbState(decaySec: 4.75, mix: 0.37),
                    delay: DelayState(timeSec: 0.70, feedback: 0.67, mix: 0.57),
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0.19),
                    bundledSampleName: "JG Dub Wave-2",
                    lfos: [
                    nil,
                    LfoState(shape: .sampleAndHold,
                         targets: [.None, .pitch],
                         rateHz: 0.32,
                         depth: 0.69),
                    LfoState(shape: .sine,
                         targets: [.None, .amplitude],
                         rateHz: 0.04,
                         depth: 0.48),
                    nil
                ]
                ),
                Voice(
                    hz: 138.59,
                    pan: 0.30,
                    wave: .sine,
                    startDelaySec: 120,
                    playDurationSec: 60,
                    replayCount: 5,
                    chorus: ChorusState(rateHz: 0.50, depth: 0.40, width: 0.70, mix: 0),
                    lfos: [
                    LfoState(shape: .square,
                         targets: [.None, .amplitude],
                         rateHz: 1.53,
                         depth: 0.46),
                    LfoState(shape: .sampleAndHold,
                         targets: [.None, .pitch],
                         rateHz: 2.79,
                         depth: 1.00),
                    nil,
                    nil
                ]
                )
               ]),
